### ISSUE TITLE
Oh, My god, you just load the image and shown it with groundtruth ???

### ISSUE THREAD

**Issue by wangxiao5791509** [nrupatunga/PY-GOTURN#1]
Oh, My god, you just load the image and shown it with groundtruth ??? Damn it ...

**Comment by nrupatunga** [comment]
@wangxiao5791509 Its in the development phase, please wait for further updates

**Comment by wangxiao5791509** [comment]
Ok, I know, and Good Luck !

**Comment by SMZCC** [comment]
Did you mean the function of show_tracker_vot.sh @wangxiao5791509   ?

**Comment by wangxiao5791509** [comment]
This code not finished yet. It can not work and only shown the groundtruth, not the tracking results of GOTURN .... @SMZCC

**Comment by nrupatunga** [comment]
@wangxiao5791509 Check the updated repository [goturn-0.1] (https://github.com/nrupatunga/PY-GOTURN)

@SMZCC Current repository has the functionality, feel free to check and let me know if you face any issues.

**Comment by SMZCC** [comment]
- I have known ,thanks.
- Just now, I have proposed an issue ,please help me figure out what's wrong?  @nrupatunga
