### ISSUE TITLE
Has anyone produced the results?

### ISSUE THREAD

**Issue by theodoruszq** [nrupatunga/PY-GOTURN#11]
Recently I really get interests on this research. The C++ version really wastes much time to compile and config. But I am still wondering is there anyone who gets the almost performance results of origin repository?

**Comment by pmixer** [comment]
@sydney0zq C++ version is user-friendly if you have already configured caffe, sorry for the late reply but the performance on OTB is just slightly worse than expected, while it may depends on training iteration number and even my GPU device.

**Comment by theodoruszq** [comment]
Oh, it seems that I have already reproduce the origin results on VOT15, even higher by 1% performance. Sorry for the not timely issue.

**Comment by LiangXu123** [comment]
@sydney0zq  Hi,HOW did you reproduce the result on VOT2015 ,have  you make any changes to this repo ? and I  find  two issues raised by you:#15 and #14, did you find out that matters?

I am really curious about whether  this repo works. Thank you very much
