### ISSUE TITLE
How to try on videos with no ground truth?

### ISSUE THREAD

**Issue by arasharchor** [nrupatunga/PY-GOTURN#18]
Hi,

I am working on object tracking in aerial videos. I want to try GOTURN on such videos, but none of them is included in VOT14. How can I try new videos?

**Comment by BigPuns** [comment]
preprocess the video like VOT14, give first frame groudtruth. run the demo after modify the video path

**Comment by arasharchor** [comment]
@BigPuns great hint. thanks. I am new into VOT14 and worked mostly on detection. Can you please guide me how to do preprocessing like VOT14?

**Comment by BigPuns** [comment]
give your video frame object bbox save in groundtruth.txt, the save type is "xmin, ymin, xmin, ymax, xmax, ymin, xmax, ymax"， you can read the source code in  scr/loader/loader_vot.cpp。

**Comment by arasharchor** [comment]
@BigPuns thanks a lot for your help.
