### ISSUE TITLE
why the train loss doesn't converge?

### ISSUE THREAD

**Issue by 3bobo** [nrupatunga/PY-GOTURN#19]
I run the `train.py` without imagenet datasets and init model , all I have is alov datasets, but after 60000 iterations, I notice that the net's  loss is all around 200, I try the snapshot caffemodel to track but they  all go badly, is it because of the missing of the init caffemode or the imagenet datasets? thank you for your help!

**Comment by nrupatunga** [comment]
1. Use Init model, along with alov dataset, but it might not generalise well because it might not be able to track objects that aren't there in the dataset. 
2. Should use imagenet, it helps to avoid overfitting.
