### ISSUE TITLE
error while testing

### ISSUE THREAD

**Issue by mad0511** [nrupatunga/PY-GOTURN#25]
(cvenv) D:\Tracking\py-goturn\goturn\test>python show_tracker_vot.py -p tracker.prototxt -m tracker_init.caffemodel -v test.mp4
Traceback (most recent call last):
  File "show_tracker_vot.py", line 8, in <module>
    from ..logger.logger import setup_logger
ValueError: attempted relative import beyond top-level package

This is the error I get while testing test file

**Comment by nrupatunga** [comment]
this should help
https://github.com/nrupatunga/PY-GOTURN/blob/goturn-dev/how_to_test.md

**Comment by mad0511** [comment]
> this should help
> https://github.com/nrupatunga/PY-GOTURN/blob/goturn-dev/how_to_test.md

I followed all those steps but not working, showing the same error
