### ISSUE TITLE
PyTorch implementation link broken

### ISSUE THREAD

**Issue by mdifatta** [nrupatunga/PY-GOTURN#27]
I was looking for the PyTorch implementation of GOTURN but the link provided seems to be broken. I noticed the link was added just 3 days ago, maybe it's just a matter of time but, has anyone managed to access that link? Maybe it's just that the repository is private.

**Comment by nrupatunga** [comment]
Hi, sorry for the confusion. I'm working on releasing the code by the end of this month. 

Please reopen the issue, if you don't see the update.

**Comment by mdifatta** [comment]
Got it, missed that info.
I look forward to take a look at you work.
Good job.

Mattia Di Fatta

Sent from my iPhone

On Mar 10, 2020, at 11:21 AM, Nrupatunga <notifications@github.com> wrote:

﻿

Hi, sorry for the confusion. I'm working on releasing the code by the end of this month.

Please reopen the issue, if you don't see the update.

**Comment by nrupatunga** [comment]
Hi @mdifatta. The PyTorch version is up. 
https://github.com/nrupatunga/goturn-pytorch

**Comment by mdifatta** [comment]
Great.
Thank you.
________________________________
Da: Nrupatunga <notifications@github.com>
Inviato: giovedì 2 aprile 2020 14:41
A: nrupatunga/PY-GOTURN <PY-GOTURN@noreply.github.com>
Cc: Mattia Di Fatta <mattia.difatta@mail.polimi.it>; Mention <mention@noreply.github.com>
Oggetto: Re: [nrupatunga/PY-GOTURN] PyTorch implementation link broken (#27)


Hi @mdifatta<https://github.com/mdifatta>. The PyTorch version is up.
https://github.com/nrupatunga/goturn-pytorch
