### ISSUE TITLE
What should I get if i run 'bash  show_tracker_vot.sh'?

### ISSUE THREAD

**Issue by flyingmoth** [nrupatunga/PY-GOTURN#4]
After I run the  'bash  show_tracker_vot.sh', I got nothing.  So what is the output?

**Comment by nrupatunga** [comment]
Did you follow this guide?

[https://github.com/nrupatunga/PY-GOTURN/blob/goturn-0.1/how_to_test.md](https://github.com/nrupatunga/PY-GOTURN/blob/goturn-0.1/how_to_test.md)

**Comment by flyingmoth** [comment]
@nrupatunga  It has been solved, I used the wrong path.
