### ISSUE TITLE
problem in goturn/train/train.py

### ISSUE THREAD

**Issue by BigPuns** [nrupatunga/PY-GOTURN#8]
In function train_video, the param of tracker_trainer.train(image_prev, image_curr, bbox_prev, bbox_prev) is wrong? maybe the second bbox_prev is bbox_curr? In GOTURN C++ source code, here is( tracker_trainer->Train(image_prev, image_curr, bbox_prev, bbox_curr);

**Comment by nrupatunga** [comment]
For the first frame there is no previous available frame, so bbox_curr = bbox_prev.

**Comment by BigPuns** [comment]
The train_video function sets the frame 0 to (len(annotations) -1) is the prev frame, and frame 1 to len(annotations) is the curr frame. so bbox_curr and bbox_prev is exist. this is not correct, which is different from GOTURN C++ source code.

**Comment by nrupatunga** [comment]
Hi, thank you for noticing, I saw train_video had this bug. It should be fixed now
